name: Golang CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # Запускается, когда добавляется тег, начинающийся с 'v'
    branches:
      - main  # Запускается при пуше в ветку main

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v4
      - name: Set working directory
        run: cd ./C:/Projects(YandexPracticum)/final-main
      - name: Set up Go environment
        run: |
          go mod tidy
          go mod verify
      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test -v ./...

  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test  # Сначала нужно пройти тесты, прежде чем публиковать
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_MANUCHEHR }}  # Укажите ваш username Docker Hub
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  # Укажите ваш токен доступа

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_MANUCHEHR }}/hello-golang:${{ github.ref_name }}  # Тег будет соответствовать имени тега
